// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","name":"graph","parentId":"@@/global-layout","id":"1"},"2":{"path":"/native-nodes","name":"native nodes","parentId":"@@/global-layout","id":"2"},"3":{"path":"/custom-nodes","name":"custom nodes","parentId":"@@/global-layout","id":"3"},"4":{"path":"custom-nodes","redirect":"custom-nodes/rect","parentId":"3","id":"4"},"5":{"path":"/custom-nodes/rect","name":"矩形节点","parentId":"3","id":"5"},"6":{"path":"/custom-nodes/ellipse","name":"椭圆节点","parentId":"3","id":"6"},"7":{"path":"/custom-nodes/icon","name":"图标节点","parentId":"3","id":"7"},"8":{"path":"/custom-nodes/image","name":"图像节点","parentId":"3","id":"8"},"9":{"path":"/custom-nodes/html","name":"HTML节点","parentId":"3","id":"9"},"10":{"path":"/custom-nodes/theme","name":"自定义主题","parentId":"3","id":"10"},"11":{"path":"/react","name":"react node registry","parentId":"@@/global-layout","id":"11"},"12":{"path":"react","redirect":"react/custom","parentId":"11","id":"12"},"13":{"path":"/react/custom","name":"自定义 React 节点","parentId":"11","id":"13"},"14":{"path":"/react/portal","name":"React Portal节点","parentId":"11","id":"14"},"15":{"name":"official extensions","path":"/extension","parentId":"@@/global-layout","id":"15"},"16":{"path":"extension","redirect":"extension/control","parentId":"15","id":"16"},"17":{"path":"/extension/control","name":"Control 插件","parentId":"15","id":"17"},"18":{"path":"/extension/menu","name":"Menu 插件","parentId":"15","id":"18"},"19":{"path":"/extension/dnd-panel","name":"DndPanel 插件","parentId":"15","id":"19"},"20":{"path":"/extension/bpmn","name":"BPMN 插件","parentId":"15","id":"20"},"21":{"path":"/extension/group","name":"Group 插件","parentId":"15","id":"21"},"22":{"path":"/extension/selection-select","name":"SelectionSelect 插件","parentId":"15","id":"22"},"23":{"path":"/extension/mini-map","name":"MiniMap 插件","parentId":"15","id":"23"},"@@/global-layout":{"id":"@@/global-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "p__graph__index" */'@/pages/graph/index.tsx')),
'2': React.lazy(() => import(/* webpackChunkName: "p__nodes__native__index" */'@/pages/nodes/native/index.tsx')),
'3': React.lazy(() => import('./EmptyRoute')),
'4': React.lazy(() => import('./EmptyRoute')),
'5': React.lazy(() => import(/* webpackChunkName: "p__nodes__custom__rect__index" */'@/pages/nodes/custom/rect/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__nodes__custom__ellipse__index" */'@/pages/nodes/custom/ellipse/index.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__nodes__custom__icon__index" */'@/pages/nodes/custom/icon/index.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__nodes__custom__image__index" */'@/pages/nodes/custom/image/index.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__nodes__custom__html__index" */'@/pages/nodes/custom/html/index.tsx')),
'10': React.lazy(() => import(/* webpackChunkName: "p__nodes__custom__theme__index" */'@/pages/nodes/custom/theme/index.tsx')),
'11': React.lazy(() => import('./EmptyRoute')),
'12': React.lazy(() => import('./EmptyRoute')),
'13': React.lazy(() => import(/* webpackChunkName: "p__react__index" */'@/pages/react/index.tsx')),
'14': React.lazy(() => import(/* webpackChunkName: "p__react__Portal" */'@/pages/react/Portal.tsx')),
'15': React.lazy(() => import('./EmptyRoute')),
'16': React.lazy(() => import('./EmptyRoute')),
'17': React.lazy(() => import(/* webpackChunkName: "p__extensions__control__index" */'@/pages/extensions/control/index.tsx')),
'18': React.lazy(() => import(/* webpackChunkName: "p__extensions__menu__index" */'@/pages/extensions/menu/index.tsx')),
'19': React.lazy(() => import(/* webpackChunkName: "p__extensions__dnd-panel__index" */'@/pages/extensions/dnd-panel/index.tsx')),
'20': React.lazy(() => import(/* webpackChunkName: "p__extensions__bpmn__index" */'@/pages/extensions/bpmn/index.tsx')),
'21': React.lazy(() => import(/* webpackChunkName: "p__extensions__group__index" */'@/pages/extensions/group/index.tsx')),
'22': React.lazy(() => import(/* webpackChunkName: "p__extensions__selection-select__index" */'@/pages/extensions/selection-select/index.tsx')),
'23': React.lazy(() => import(/* webpackChunkName: "p__extensions__mini-map__index" */'@/pages/extensions/mini-map/index.tsx')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow/examples/feature-examples/src/layouts/index.tsx')),
},
  };
}
